name: minove
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  waterfall_flow: 3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: FredokaOne
      fonts:
        - asset: assets/fonts/FredokaOne-Regular.ttf
    - family: PatrickHand
      fonts:
        - asset: assets/fonts/PatrickHand-Regular.ttf